name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build (${{ matrix.arch }}-${{ matrix.os }}) on ${{ matrix.runner }}
    if:
      "!contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.event.head_commit.message, 'docs')"
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { os: "linux", arch: "x86_64", runner: "ubuntu-24.04" }
          - { os: "linux", arch: "x86_64", runner: "ubuntu-22.04" }
          - { os: "linux", arch: "aarch64", runner: "ubuntu-24.04-arm" }
          - { os: "linux", arch: "aarch64", runner: "ubuntu-22.04-arm" }
          - { os: "macos", arch: "x86_64", runner: "macos-13" }
          - { os: "macos", arch: "aarch64", runner: "macos-14" }
          - { os: "macos", arch: "aarch64", runner: "macos-15" }
          - { os: "windows", arch: "x86_64", runner: "windows-2025" }
          - { os: "windows", arch: "x86_64", runner: "windows-2022" }
          - { os: "windows", arch: "aarch64", runner: "windows-11-arm" }
      fail-fast: false

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up Zig
        uses: mlugg/setup-zig@v2.0.4

      - name: Build
        run: zig build

  test:
    name: Test (${{ matrix.arch }}-${{ matrix.os }}) on ${{ matrix.runner }}
    if:
      "!contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !startsWith(github.event.head_commit.message, 'docs')"
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - { os: "linux", arch: "x86_64", runner: "ubuntu-24.04" }
          - { os: "linux", arch: "x86_64", runner: "ubuntu-22.04" }
          - { os: "linux", arch: "aarch64", runner: "ubuntu-24.04-arm" }
          - { os: "linux", arch: "aarch64", runner: "ubuntu-22.04-arm" }
          - { os: "macos", arch: "x86_64", runner: "macos-13" }
          - { os: "macos", arch: "aarch64", runner: "macos-14" }
          - { os: "macos", arch: "aarch64", runner: "macos-15" }
          - { os: "windows", arch: "x86_64", runner: "windows-2025" }
          - { os: "windows", arch: "x86_64", runner: "windows-2022" }
          - { os: "windows", arch: "aarch64", runner: "windows-11-arm" }
      fail-fast: false

    steps:
      - name: Clone the source code
        uses: actions/checkout@v4.2.2

      - name: Set up Zig
        uses: mlugg/setup-zig@v2.0.4

      - name: Run the unit tests
        run: zig build test --summary all
