linters:
  enable-all: true
  disable:
    - godox

linters-settings:
  cyclop:
    # max-complexity: 10
    max-complexity: 20
  decorder:
    dec-order:
      - type
      - const
      - var
      - func
    ignore-underscore-vars: false
    disable-dec-order-check: false
    disable-init-func-first-check: false
    disable-dec-num-check: true
    disable-type-dec-num-check: false
    disable-const-dec-num-check: false
    disable-var-dec-num-check: false
  depguard:
    rules:
      Main:
        list-mode: strict
        allow:
          - $gostd
          - github.com/anttikivi
          - github.com/cli/safeexec
          - github.com/fatih/color
          - github.com/spf13/cobra
          - github.com/spf13/pflag
          - github.com/spf13/viper
  funlen:
    lines: 100
    statements: 50
    ignore-comments: true
  gocritic:
    enable-all: true
    disabled-checks:
      - commentedOutCode
      - unnamedResult
  varnamelen:
    max-distance: 30
    min-name-length: 3
    ignore-decls:
      - b *testing.B
      - err error
      - i int
      - sb strings.Builder
      - T any
      - t *testing.T

issues:
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - dupword
        - funlen
        - gochecknoglobals
        - lll
run:
  timeout: "1m"
