name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { goos: "freebsd", goarch: "386", os: "ubuntu-latest" }
          - { goos: "freebsd", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "freebsd", goarch: "arm", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "386", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "arm", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "arm64", os: "ubuntu-latest" }
          - { goos: "openbsd", goarch: "386", os: "ubuntu-latest" }
          - { goos: "openbsd", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "solaris", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "windows", goarch: "386", os: "windows-latest" }
          - { goos: "windows", goarch: "amd64", os: "windows-latest" }
          - { goos: "darwin", goarch: "amd64", os: "macos-latest" }
          - { goos: "darwin", goarch: "arm64", os: "macos-latest" }
      fail-fast: false

    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4.2.2

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.2.0
        with:
          go-version-file: go.mod

      - name: Cache the Go modules
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify and download dependencies
        run: |
          go mod verify
          go mod download

      - name: Build Reginald
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v .

      - name: Run the version command
        run: ./reginald version

  make-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - { goos: "freebsd", goarch: "386", os: "ubuntu-latest" }
          - { goos: "freebsd", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "freebsd", goarch: "arm", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "386", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "arm", os: "ubuntu-latest" }
          - { goos: "linux", goarch: "arm64", os: "ubuntu-latest" }
          - { goos: "openbsd", goarch: "386", os: "ubuntu-latest" }
          - { goos: "openbsd", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "solaris", goarch: "amd64", os: "ubuntu-latest" }
          - { goos: "windows", goarch: "386", os: "windows-latest" }
          - { goos: "windows", goarch: "amd64", os: "windows-latest" }
          - { goos: "darwin", goarch: "amd64", os: "macos-latest" }
          - { goos: "darwin", goarch: "arm64", os: "macos-latest" }
      fail-fast: false

    steps:
      - name: Fetch the source code
        uses: actions/checkout@v4.2.2

      - name: Install the Go toolchain
        uses: actions/setup-go@v5.2.0
        with:
          go-version-file: go.mod

      - name: Cache the Go modules
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Verify and download dependencies
        run: |
          go mod verify
          go mod download

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build

      - name: Run the version command
        if: ${{ runner.os != 'Windows' }}
        run: ./reginald version

      - name: Run the version command on Windows
        if: ${{ runner.os == 'Windows' }}
        run: .\reginald.exe version
